In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore
from sklearn import preprocessing
from sklearn.metrics import r2_score 
from sklearn.preprocessing import QuantileTransformer

In [ ]:
df1=pd.read_csv(r"C:\Users\BAPS\Desktop\Python\Datasets\SeoulBikeData.csv")
df1

,Date,Rented Bike Count,Hour,Temperature(C),Humidity(%),Wind speed (m/s),Visibility (m),Dew point temperature(C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,1003,19,4.2,34,2.6,1894,-10.3,0.0,0.0,0.0,Autumn,No Holiday,Yes
8756,30/11/2018,764,20,3.4,37,2.3,2000,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8757,30/11/2018,694,21,2.6,39,0.3,1968,-9.9,0.0,0.0,0.0,Autumn,No Holiday,Yes
8758,30/11/2018,712,22,2.1,41,1.0,1859,-9.8,0.0,0.0,0.0,Autumn,No Holiday,Yes
8759,30/11/2018,584,23,1.9,43,1.3,1909,-9.3,0.0,0.0,0.0,Autumn,No Holiday,Yes

## Implementation of cat boost without encoding the dataset

In [4]:
df1.drop(["Date"],axis=1,inplace=True)

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X=df1.drop(["Rented Bike Count"],axis=1)
Y=df1["Rented Bike Count"]
lr_model=LinearRegression()
x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.8)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7008, 12)
(1752, 12)
(7008,)
(1752,)

In [ ]:
from catboost import CatBoostRegressor

In [10]:
cat_features =["Seasons","Functioning Day","Holiday"]

In [11]:
one_hot_max_size = 5
ctb=CatBoostRegressor(iterations=100, depth=6, learning_rate=0.1,
                    verbose=False, cat_features=cat_features, one_hot_max_size=one_hot_max_size,loss_function='RMSE')

In [ ]:
ctb.fit(x_train,y_train)
y_predict_train = ctb.predict(x_train)
y_predict_test = ctb.predict(x_test)
print("Train R2:", r2_score(y_train, y_predict_train))
print("Test R2 :", r2_score(y_test, y_predict_test))

Train R2: 0.8796619953080699
Test R2 : 0.8618746802002303

In [9]:
df1.Seasons.value_counts()

Seasons
Spring    2208
Summer    2208
Autumn    2184
Winter    2160
Name: count, dtype: int64